site_name: MISIS Bot Deployment Guide

# repo_url: https://github.com/0xb1b1/nixos-config
# repo_name: 0xb1b1/nixos-config

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light theme
      primary: teal
      accent: lime

